# Generated by Django 3.0.5 on 2020-04-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('address', models.TextField(null=True, verbose_name='Dirección')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último acceso')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=True)),
                ('cover_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_img', to='images.Image')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('user_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_img', to='images.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
