# Generated by Django 3.0.5 on 2020-04-17 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cover_img',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_img', to='images.Image'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_img',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_img', to='images.Image'),
        ),
    ]
