# Generated by Django 3.0.3 on 2020-03-26 03:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200315_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(default='profile_img/default.png', upload_to=account.models.images_directory_path),
        ),
    ]
