# Generated by Django 3.0.3 on 2020-05-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={'verbose_name': 'Intercambio Lempiras', 'verbose_name_plural': 'Intercambios de Moneda'},
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange',
            field=models.FloatField(verbose_name='Intercambio a Lempiras'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sign',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Signo'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Moneda'),
        ),
    ]
