# Generated by Django 3.0.3 on 2020-04-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='sign',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
