# Generated by Django 3.0.3 on 2020-05-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_disable_ads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disable_ads',
        ),
    ]
