# Generated by Django 3.0.5 on 2020-04-17 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('stor_cover_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_cover_img', to='images.Image')),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('store_profile_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_profile_img', to='images.Image')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='UsersXStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario por Tienda',
                'verbose_name_plural': 'Usuarios por Tiendas',
            },
        ),
    ]
