# Generated by Django 3.0.4 on 2020-05-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200501_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
