# Generated by Django 3.0.4 on 2020-05-06 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.CharField(max_length=20)),
                ('comment', models.TextField(null=True, verbose_name='Comentario')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion')),
                ('user_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_complaint', to=settings.AUTH_USER_MODEL, verbose_name='Denunciante')),
            ],
            options={
                'verbose_name': 'Denunciante',
                'verbose_name_plural': 'Denuncias',
            },
        ),
    ]
