# Generated by Django 3.0.4 on 2020-05-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='election',
            new_name='problem',
        ),
    ]
