# Generated by Django 3.0.4 on 2020-05-13 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200506_1420'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0004_auto_20200507_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=20, verbose_name='Problema')),
                ('comment', models.TextField(null=True, verbose_name='Comentario')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion')),
                ('reported_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_store', to='store.Store', verbose_name='Tienda denunciada')),
                ('reporting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_user', to=settings.AUTH_USER_MODEL, verbose_name='Denunciador')),
            ],
            options={
                'verbose_name': 'Denunciante',
                'verbose_name_plural': 'Denunciantes por Tienda',
            },
        ),
    ]
