# Generated by Django 3.0.5 on 2020-04-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyConversion',
        ),
    ]
