# Generated by Django 3.0.3 on 2020-05-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_delete_currencyconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
