# Generated by Django 3.0.3 on 2020-05-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Tiempo Inhabilitar', 'verbose_name_plural': 'Tiempo Tiempo Inhabilitar'},
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.IntegerField(verbose_name='Dias para desabilitar anuncio'),
        ),
    ]
