# Generated by Django 3.0.3 on 2020-05-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_auto_20200506_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='Time_ads',
        ),
    ]
