# Generated by Django 3.0.3 on 2020-05-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_delete_time_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='disable_ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='Desabilitar Anuncio')),
            ],
        ),
    ]
