# Generated by Django 3.0.3 on 2020-05-07 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_disable_ads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disable_ads',
            old_name='time',
            new_name='time_dis',
        ),
    ]
