# Generated by Django 3.0.4 on 2020-05-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_disable_ads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disable_ads',
            options={'verbose_name': 'Dias para desabilitar anuncios'},
        ),
    ]
