# Generated by Django 3.0.3 on 2020-03-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0021_auto_20200316_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='id_currency',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ad.Currency'),
        ),
    ]
