# Generated by Django 3.0.3 on 2020-03-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0022_auto_20200324_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='id_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Currency'),
        ),
    ]
