# Generated by Django 3.0.4 on 2020-04-16 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_store_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('comments', models.TextField(null=True)),
                ('evaluated_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
                ('evaluated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_user', to=settings.AUTH_USER_MODEL)),
                ('evaluator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rating evaluated',
                'verbose_name_plural': 'Ratings User',
            },
        ),
    ]
