# Generated by Django 3.0.3 on 2020-05-02 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20200417_0104'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='evaluated_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='Tienda Evaluada'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='evaluated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_user', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='evaluator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_user', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='points',
            field=models.IntegerField(verbose_name='Puntos'),
        ),
    ]
