# Generated by Django 3.0.4 on 2020-05-12 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_auto_20200506_1420'),
        ('rating', '0002_auto_20200501_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Puntos')),
                ('comment', models.TextField(null=True, verbose_name='Comentario')),
                ('evaluated_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_store', to='store.Store', verbose_name='Tienda Evaluada')),
                ('evaluator_user_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_user_store', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
            ],
            options={
                'verbose_name': 'Evaluación Tiendas',
                'verbose_name_plural': 'Evaluaciónes de Tiendas',
            },
        ),
    ]
