# Generated by Django 3.0.3 on 2020-05-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
    ]
