# Generated by Django 3.0.3 on 2020-05-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disable_ads',
        ),
    ]
